#!/usr/bin/env bash

theme=$(dirname $0)/./theme.rasi
prompt="Goodbyaa ỤnỤ"
options="Let me think again\nExit i3WM"
cancel="$(echo -e "$options" | grep 'think')"
confirm="$(echo -e "$options" | grep 'Exit')"

returnn="~/.config/rofi/powermenu/powermenu"

choosen=$(echo -e "$options" | rofi -dmenu -p "$prompt" -theme $theme)

case "$choosen" in
    "$cancel") exec $returnn
    ;;
    "$confirm") xfce4-screensaver-command --lock & sleep 1; i3-msg exit
    ;;
esac
