#!/usr/bin/env bash

theme=$(dirname $0)/./theme.rasi
prompt="Goodbya OWO"
options="Let me think again\nTerminate Termux."
cancel="$(echo -e "$options" | grep 'think')"
confirm="$(echo -e "$options" | grep 'Terminate')"

returnn="~/.config/rofi/powermenu/powermenu"

choosen=$(echo -e "$options" | rofi -dmenu -p "$prompt" -theme $theme)

case "$choosen" in
    "$cancel") exec $returnn
    ;;
    "$confirm") xfce4-screensaver-command --lock & sleep 1; killall -q "com.termux"
    ;;
esac

