#!/usr/bin/env bash

WallDir=$1
prompt="Change Wallpaper:"
theme=$(dirname $0)/./theme.rasi

choose=$(ls -1 $WallDir | grep -E '\.(png|jpg|jpeg)$' | rofi -dmenu -theme "$theme" -p "$prompt")

if [ $? -ne 0 ]; then
    echo "Session cancelled."
    exit 0
fi

echo "$(realpath $WallDir)/$choose" > ~/.local/etc/wallpaper
$(wallpaper-launch)
